AWSTemplateFormatVersion: '2010-09-09'
Description: Simple EC2 instance

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b09ffb6d8b58ca91  # Amazon Linux 
      InstanceType: t2.micro
